package com.telelibre

import android.util.Base64 // Importante para el atob()
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.loadExtractor
import org.jsoup.nodes.Element
import java.nio.charset.StandardCharsets

class TeleLibre : MainAPI() {

    override var mainUrl = "https://tele-libre.fans"
        override var name = "Tele-Libre"
            override val hasMainPage = true
                override var lang = "es"
                    override val hasQuickSearch = true
                        // Cambiamos a LiveStream ya que es televisión en vivo
                            override val supportedTypes = setOf(TvType.LiveStream)

                                override val mainPage = mainPageOf(
                                        "" to "Canales destacados"
                                            )

                                                override suspend fun getMainPage(
                                                        page: Int,
                                                                request: MainPageRequest
                                                                    ): HomePageResponse {
                                                                            val document = app.get(mainUrl).document
                                                                                    [span_1](start_span)// Usamos el selector detectado en el mapa técnico[span_1](end_span)
                                                                                            val home = document.select("img.w-28.h-28.object-contain.rounded")
                                                                                                        .mapNotNull { it.parent()?.toSearchResult() } // Buscamos el link <a> padre
                                                                                                                    .distinctBy { it.url }

                                                                                                                            return newHomePageResponse(request.name, home, false)
                                                                                                                                }

                                                                                                                                    private fun Element.toSearchResult(): SearchResponse {
                                                                                                                                            [span_2](start_span)// Extraemos la información basándonos en el mapa técnico[span_2](end_span)
                                                                                                                                                    val title = select("img").attr("alt").ifEmpty { "Canal" }
                                                                                                                                                            val href = attr("href")
                                                                                                                                                                    val poster = select("img").attr("src")

                                                                                                                                                                            return newLiveSearchResponse(title, fixUrl(href), TvType.LiveStream) { 
                                                                                                                                                                                        posterUrl = fixUrl(poster) 
                                                                                                                                                                                                }
                                                                                                                                                                                                    }

                                                                                                                                                                                                        override suspend fun search(query: String): List<SearchResponse> {
                                                                                                                                                                                                                // Basado en el HTML proporcionado, el buscador usa un input simple
                                                                                                                                                                                                                        val document = app.get(mainUrl).document
                                                                                                                                                                                                                                return document.select("img.w-28.h-28.object-contain.rounded")
                                                                                                                                                                                                                                            .mapNotNull { it.parent()?.toSearchResult() }
                                                                                                                                                                                                                                                        .filter { it.name.contains(query, ignoreCase = true) }
                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                override suspend fun load(url: String): LoadResponse {
                                                                                                                                                                                                                                                                        val document = app.get(url).document
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        [span_3](start_span)// Información del canal extraída del card-body del HTML[span_3](end_span)
                                                                                                                                                                                                                                                                                                val title = document.selectFirst("h3.mb-3")?.text()?.replace("Estás viendo el Canal:", "")?.trim() 
                                                                                                                                                                                                                                                                                                            ?: "Canal TV"
                                                                                                                                                                                                                                                                                                                    val poster = document.selectFirst(".logoCanal img")?.attr("src")
                                                                                                                                                                                                                                                                                                                            val description = document.selectFirst(".card-text")?.text()

                                                                                                                                                                                                                                                                                                                                    // Para TV en vivo, creamos un único "episodio" que representa el stream
                                                                                                                                                                                                                                                                                                                                            val episodes = listOf(
                                                                                                                                                                                                                                                                                                                                                        newEpisode(url) { 
                                                                                                                                                                                                                                                                                                                                                                        name = "Ver en Vivo"
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                            )

                                                                                                                                                                                                                                                                                                                                                                                                    return newLiveLoadResponse(title, url, TvType.LiveStream, episodes) {
                                                                                                                                                                                                                                                                                                                                                                                                                posterUrl = fixUrl(poster ?: "")
                                                                                                                                                                                                                                                                                                                                                                                                                            plot = description
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                            override suspend fun loadLinks(
                                                                                                                                                                                                                                                                                                                                                                                                                                                    data: String,
                                                                                                                                                                                                                                                                                                                                                                                                                                                            isCasting: Boolean,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    subtitleCallback: (SubtitleFile) -> Unit,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            callback: (ExtractorLink) -> Unit
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ): Boolean {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val response = app.get(data).text
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val videoLinks = mutableSetOf<String>()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [span_4](start_span)// Lógica de decodificación Base64 detectada en el HTML[span_4](end_span)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Buscamos parámetros 'embed' o 'r' en el script de la página
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val regex = Regex("""(?:embed|r)\s*=\s*['"]([^'"]+)['"]""")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                regex.findAll(response).forEach { match ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val encodedData = match.groupValues[1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [span_5](start_span)// El equivalente a atob() de JavaScript[span_5](end_span)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val decodedUrl = String(Base64.decode(encodedData, Base64.DEFAULT), StandardCharsets.UTF_8)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (decodedUrl.startsWith("http")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            videoLinks.add(decodedUrl)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch (_: Exception) {}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // También buscamos iframes directos por si acaso
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Regex("""<iframe[^>]+src=["'](https?://[^"']+)["']""", RegexOption.IGNORE_CASE).findAll(response).forEach {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val link = it.groupValues[1]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!link.contains("google") && !link.contains("adskeeper")) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        videoLinks.add(link)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    videoLinks.forEach { link ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                loadExtractor(link, data, subtitleCallback, callback)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return videoLinks.isNotEmpty()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    